name: Run Unit tests

on: [push]

jobs:
  install-and-tests:
    name: Installing dependencies and running tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name:  Installing dependencies
        run:  npm install
      - name:  Running unit tests
        run:  npm run unit
      - name:  Running e2e tests
        run:  |
          npm run e2e-test
          if [ "$(ls -A test/e2e/out)" ]; then echo "Not Empty"; else echo "Allure output directory is empty"; exit 1; fi